apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "steward.fullname" . }}
  labels:
    {{- include "steward.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "steward.api.name" . }}
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "steward.web.name" . }}
                port:
                  name: http
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      {{- if .Values.ingress.tlsSecretName }}
      secretName: {{ .Values.ingress.tlsSecretName }}
      {{- end }}
