{{- $secretName := printf "%s-jwt" (include "steward.fullname" .) }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "steward.labels" . | nindent 4 }}
type: Opaque
data:
  key: {{ if $existing }}{{ index $existing.data "key" }}{{ else }}{{ randAlphaNum 64 | b64enc }}{{ end }}
