apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "steward.web.name" . }}
  labels:
    {{- include "steward.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "steward.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "steward.labels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      containers:
        - name: web
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.web.port }}
              protocol: TCP
          env:
            - name: API_BASE_URL
              {{- $scheme := ternary "https" "http" (not (empty .Values.ingress.tlsSecretName)) }}
              value: {{ .Values.web.apiBaseUrl | default (printf "%s://%s" $scheme .Values.ingress.host) | quote }}
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
