/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/households/{householdId}/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    assetType?: components["schemas"]["AssetType"];
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    householdId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    householdId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateAssetRequest"];
                    "text/json": components["schemas"]["CreateAssetRequest"];
                    "application/*+json": components["schemas"]["CreateAssetRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/households/{householdId}/assets/{assetId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    householdId: string;
                    assetId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    householdId: string;
                    assetId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateAssetRequest"];
                    "text/json": components["schemas"]["UpdateAssetRequest"];
                    "application/*+json": components["schemas"]["UpdateAssetRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    householdId: string;
                    assetId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                    "text/json": components["schemas"]["RegisterRequest"];
                    "application/*+json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/oauth/{provider}/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    provider: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/oauth/{provider}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    provider: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/oauth/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OAuthExchangeRequest"];
                    "text/json": components["schemas"]["OAuthExchangeRequest"];
                    "application/*+json": components["schemas"]["OAuthExchangeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/invites/{code}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    code: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/households/{householdId}/assets/{assetId}/engines/{engineId}/hours-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    householdId: string;
                    assetId: string;
                    engineId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    householdId: string;
                    assetId: string;
                    engineId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateEngineHoursLogRequest"];
                    "text/json": components["schemas"]["CreateEngineHoursLogRequest"];
                    "application/*+json": components["schemas"]["CreateEngineHoursLogRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/households/{householdId}/assets/{assetId}/engines/{engineId}/hours-logs/{hoursLogId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    householdId: string;
                    assetId: string;
                    engineId: string;
                    hoursLogId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateEngineHoursLogRequest"];
                    "text/json": components["schemas"]["UpdateEngineHoursLogRequest"];
                    "application/*+json": components["schemas"]["UpdateEngineHoursLogRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    householdId: string;
                    assetId: string;
                    engineId: string;
                    hoursLogId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/households/{householdId}/assets/{assetId}/engines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    householdId: string;
                    assetId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    householdId: string;
                    assetId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateEngineRequest"];
                    "text/json": components["schemas"]["CreateEngineRequest"];
                    "application/*+json": components["schemas"]["CreateEngineRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/households/{householdId}/assets/{assetId}/engines/{engineId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    householdId: string;
                    assetId: string;
                    engineId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateEngineRequest"];
                    "text/json": components["schemas"]["UpdateEngineRequest"];
                    "application/*+json": components["schemas"]["UpdateEngineRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    householdId: string;
                    assetId: string;
                    engineId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/households/{householdId}/assets/{assetId}/engines/{engineId}/retire": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    householdId: string;
                    assetId: string;
                    engineId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/households/{householdId}/assets/{assetId}/engines/{engineId}/reactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    householdId: string;
                    assetId: string;
                    engineId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/households/{householdId}/assets/{assetId}/fuel-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    householdId: string;
                    assetId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    householdId: string;
                    assetId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateFuelLogRequest"];
                    "text/json": components["schemas"]["CreateFuelLogRequest"];
                    "application/*+json": components["schemas"]["CreateFuelLogRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/households/{householdId}/assets/{assetId}/fuel-logs/{fuelLogId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    householdId: string;
                    assetId: string;
                    fuelLogId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateFuelLogRequest"];
                    "text/json": components["schemas"]["UpdateFuelLogRequest"];
                    "application/*+json": components["schemas"]["UpdateFuelLogRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    householdId: string;
                    assetId: string;
                    fuelLogId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/households/{householdId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    householdId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/households/{householdId}/members/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    householdId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["InviteMemberRequest"];
                    "text/json": components["schemas"]["InviteMemberRequest"];
                    "application/*+json": components["schemas"]["InviteMemberRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/households/{householdId}/invitations/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    householdId: string;
                    code: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/households/{householdId}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    householdId: string;
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/households": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateHouseholdRequest"];
                    "text/json": components["schemas"]["CreateHouseholdRequest"];
                    "application/*+json": components["schemas"]["CreateHouseholdRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/households/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateHouseholdRequest"];
                    "text/json": components["schemas"]["UpdateHouseholdRequest"];
                    "application/*+json": components["schemas"]["UpdateHouseholdRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/households/{householdId}/assets/{assetId}/mileage-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    householdId: string;
                    assetId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    householdId: string;
                    assetId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateMileageLogRequest"];
                    "text/json": components["schemas"]["CreateMileageLogRequest"];
                    "application/*+json": components["schemas"]["CreateMileageLogRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/households/{householdId}/assets/{assetId}/mileage-logs/{mileageLogId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    householdId: string;
                    assetId: string;
                    mileageLogId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateMileageLogRequest"];
                    "text/json": components["schemas"]["UpdateMileageLogRequest"];
                    "application/*+json": components["schemas"]["UpdateMileageLogRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    householdId: string;
                    assetId: string;
                    mileageLogId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    email?: string;
                    page?: number | string;
                    pageSize?: number | string;
                    "api-version"?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AssignRoleRequest"];
                    "text/json": components["schemas"]["AssignRoleRequest"];
                    "application/*+json": components["schemas"]["AssignRoleRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{id}/roles/{roleName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    id: string;
                    roleName: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/households/{householdId}/assets/{assetId}/registrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    householdId: string;
                    assetId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    householdId: string;
                    assetId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateRegistrationRequest"];
                    "text/json": components["schemas"]["CreateRegistrationRequest"];
                    "application/*+json": components["schemas"]["CreateRegistrationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/households/{householdId}/assets/{assetId}/registrations/{registrationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    householdId: string;
                    assetId: string;
                    registrationId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateRegistrationRequest"];
                    "text/json": components["schemas"]["UpdateRegistrationRequest"];
                    "application/*+json": components["schemas"]["UpdateRegistrationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    householdId: string;
                    assetId: string;
                    registrationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/households/{householdId}/assets/{assetId}/registrations/{registrationId}/document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    householdId: string;
                    assetId: string;
                    registrationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    householdId: string;
                    assetId: string;
                    registrationId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        file?: components["schemas"]["IFormFile"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    householdId: string;
                    assetId: string;
                    registrationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/households/{householdId}/assets/{assetId}/service-records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    householdId: string;
                    assetId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    householdId: string;
                    assetId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateServiceRecordRequest"];
                    "text/json": components["schemas"]["CreateServiceRecordRequest"];
                    "application/*+json": components["schemas"]["CreateServiceRecordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/households/{householdId}/assets/{assetId}/service-records/{serviceRecordId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    householdId: string;
                    assetId: string;
                    serviceRecordId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateServiceRecordRequest"];
                    "text/json": components["schemas"]["UpdateServiceRecordRequest"];
                    "application/*+json": components["schemas"]["UpdateServiceRecordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    householdId: string;
                    assetId: string;
                    serviceRecordId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/households/{householdId}/assets/{assetId}/warranties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    householdId: string;
                    assetId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    householdId: string;
                    assetId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateWarrantyRequest"];
                    "text/json": components["schemas"]["CreateWarrantyRequest"];
                    "application/*+json": components["schemas"]["CreateWarrantyRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/households/{householdId}/assets/{assetId}/warranties/{warrantyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    householdId: string;
                    assetId: string;
                    warrantyId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateWarrantyRequest"];
                    "text/json": components["schemas"]["UpdateWarrantyRequest"];
                    "application/*+json": components["schemas"]["UpdateWarrantyRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    householdId: string;
                    assetId: string;
                    warrantyId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/households/{householdId}/assets/{assetId}/warranties/{warrantyId}/document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    householdId: string;
                    assetId: string;
                    warrantyId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    householdId: string;
                    assetId: string;
                    warrantyId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        file?: components["schemas"]["IFormFile"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete: {
            parameters: {
                query?: {
                    "api-version"?: string;
                };
                header?: never;
                path: {
                    householdId: string;
                    assetId: string;
                    warrantyId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AssetType: number;
        AssignRoleRequest: {
            role: string;
        };
        CreateAssetRequest: {
            assetType: components["schemas"]["AssetType"];
            name: string;
            description: null | string;
            /** Format: int32 */
            year: null | number | string;
            photoUrl: null | string;
            usageTrackingMode: components["schemas"]["UsageTrackingMode"];
            vin: null | string;
            color: null | string;
            make: null | string;
            model: null | string;
            hin: null | string;
            hullMaterial: null | string;
            /** Format: double */
            lengthFt: null | number | string;
            /** Format: double */
            beamFt: null | number | string;
            /** Format: double */
            trackLengthIn: null | number | string;
            /** Format: double */
            ballSizeIn: null | number | string;
            /** Format: double */
            maxLoadLbs: null | number | string;
            /** Format: double */
            interiorHeightFt: null | number | string;
            /** Format: double */
            interiorLengthFt: null | number | string;
            /** Format: double */
            cuttingWidthIn: null | number | string;
            /** Format: double */
            maxPsi: null | number | string;
            /** Format: double */
            maxGpm: null | number | string;
            equipmentDescription: null | string;
        };
        CreateEngineHoursLogRequest: {
            /** Format: date */
            date: string;
            /** Format: double */
            hoursReading: null | number | string;
            /** Format: double */
            tripHours: null | number | string;
            notes: null | string;
        };
        CreateEngineRequest: {
            label: string;
            make: null | string;
            model: null | string;
            serialNumber: null | string;
            /** Format: int32 */
            year: null | number | string;
            engineType: components["schemas"]["EngineType"];
            fuelType: components["schemas"]["FuelType"];
            /** Format: int32 */
            cylinders: null | number | string;
            /** Format: double */
            displacementCc: null | number | string;
            /** Format: date */
            installedDate: null | string;
            /** Format: double */
            installedAtAssetMiles: null | number | string;
            /** Format: double */
            installedAtAssetHours: null | number | string;
        };
        CreateFuelLogRequest: {
            logType: components["schemas"]["FuelLogType"];
            /** Format: date */
            date: string;
            /** Format: double */
            volume: number | string;
            volumeUnit: components["schemas"]["VolumeUnit"];
            fuelGrade: null | string;
            /** Format: double */
            pricePerUnit: null | number | string;
            /** Format: double */
            totalCost: null | number | string;
            /** Format: double */
            milesAtLog: null | number | string;
            /** Format: double */
            hoursAtLog: null | number | string;
            /** Format: uuid */
            engineId: null | string;
            notes: null | string;
        };
        CreateHouseholdRequest: {
            name: string;
            publicSlug: string;
            isPublicVisible: boolean;
        };
        CreateMileageLogRequest: {
            /** Format: date */
            date: string;
            /** Format: double */
            odometerReading: null | number | string;
            /** Format: double */
            tripMiles: null | number | string;
            notes: null | string;
        };
        CreateRegistrationRequest: {
            registrationNumber: string;
            issuingAuthority: null | string;
            /** Format: date */
            renewedOn: null | string;
            /** Format: double */
            cost: null | number | string;
            /** Format: date */
            expiresOn: null | string;
            notes: null | string;
        };
        CreateServiceRecordRequest: {
            /** Format: date */
            date: string;
            description: string;
            providerName: null | string;
            /** Format: double */
            cost: null | number | string;
            /** Format: double */
            odometerMiles: null | number | string;
            /** Format: double */
            engineHours: null | number | string;
            /** Format: uuid */
            engineId: null | string;
            notes: null | string;
        };
        CreateWarrantyRequest: {
            provider: string;
            description: null | string;
            /** Format: date */
            startsOn: null | string;
            /** Format: date */
            expiresOn: null | string;
            notes: null | string;
        };
        EngineType: number;
        FuelLogType: number;
        FuelType: number;
        HouseholdMemberRole: number;
        /** Format: binary */
        IFormFile: string;
        InviteMemberRequest: {
            email: string;
            role: components["schemas"]["HouseholdMemberRole"];
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        OAuthExchangeRequest: {
            code: string;
        };
        RegisterRequest: {
            email: string;
            password: string;
            displayName: string;
        };
        UpdateAssetRequest: {
            assetType: null | components["schemas"]["AssetType"];
            name: string;
            description: null | string;
            /** Format: int32 */
            year: null | number | string;
            photoUrl: null | string;
            usageTrackingMode: components["schemas"]["UsageTrackingMode"];
            vin: null | string;
            color: null | string;
            make: null | string;
            model: null | string;
            hin: null | string;
            hullMaterial: null | string;
            /** Format: double */
            lengthFt: null | number | string;
            /** Format: double */
            beamFt: null | number | string;
            /** Format: double */
            trackLengthIn: null | number | string;
            /** Format: double */
            ballSizeIn: null | number | string;
            /** Format: double */
            maxLoadLbs: null | number | string;
            /** Format: double */
            interiorHeightFt: null | number | string;
            /** Format: double */
            interiorLengthFt: null | number | string;
            /** Format: double */
            cuttingWidthIn: null | number | string;
            /** Format: double */
            maxPsi: null | number | string;
            /** Format: double */
            maxGpm: null | number | string;
            equipmentDescription: null | string;
        };
        UpdateEngineHoursLogRequest: {
            /** Format: date */
            date: string;
            /** Format: double */
            hoursReading: null | number | string;
            /** Format: double */
            tripHours: null | number | string;
            notes: null | string;
        };
        UpdateEngineRequest: {
            label: string;
            make: null | string;
            model: null | string;
            serialNumber: null | string;
            /** Format: int32 */
            year: null | number | string;
            engineType: components["schemas"]["EngineType"];
            fuelType: components["schemas"]["FuelType"];
            /** Format: int32 */
            cylinders: null | number | string;
            /** Format: double */
            displacementCc: null | number | string;
            /** Format: date */
            installedDate: null | string;
            /** Format: double */
            installedAtAssetMiles: null | number | string;
            /** Format: double */
            installedAtAssetHours: null | number | string;
        };
        UpdateFuelLogRequest: {
            logType: components["schemas"]["FuelLogType"];
            /** Format: date */
            date: string;
            /** Format: double */
            volume: number | string;
            volumeUnit: components["schemas"]["VolumeUnit"];
            fuelGrade: null | string;
            /** Format: double */
            pricePerUnit: null | number | string;
            /** Format: double */
            totalCost: null | number | string;
            /** Format: double */
            milesAtLog: null | number | string;
            /** Format: double */
            hoursAtLog: null | number | string;
            /** Format: uuid */
            engineId: null | string;
            notes: null | string;
        };
        UpdateHouseholdRequest: {
            name: string;
            publicSlug: string;
            isPublicVisible: boolean;
        };
        UpdateMileageLogRequest: {
            /** Format: date */
            date: string;
            /** Format: double */
            odometerReading: null | number | string;
            /** Format: double */
            tripMiles: null | number | string;
            notes: null | string;
        };
        UpdateRegistrationRequest: {
            registrationNumber: string;
            issuingAuthority: null | string;
            /** Format: date */
            renewedOn: null | string;
            /** Format: double */
            cost: null | number | string;
            /** Format: date */
            expiresOn: null | string;
            notes: null | string;
        };
        UpdateServiceRecordRequest: {
            /** Format: date */
            date: string;
            description: string;
            providerName: null | string;
            /** Format: double */
            cost: null | number | string;
            /** Format: double */
            odometerMiles: null | number | string;
            /** Format: double */
            engineHours: null | number | string;
            /** Format: uuid */
            engineId: null | string;
            notes: null | string;
        };
        UpdateWarrantyRequest: {
            provider: string;
            description: null | string;
            /** Format: date */
            startsOn: null | string;
            /** Format: date */
            expiresOn: null | string;
            notes: null | string;
        };
        UsageTrackingMode: number;
        VolumeUnit: number;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
