import type { AssetTypeDefinition } from "@/api/types";

/// Trimmed registry for component tests; mirrors the shape served by GET /api/asset-types.
export const testAssetTypeRegistry: AssetTypeDefinition[] = [
  {
    category: "Car",
    group: "Road",
    structuralType: "Vehicle",
    displayLabel: "Car",
    defaultUsageTrackingMode: "Mileage",
    typicallyHasEngine: true,
    vinDecodeSupport: "Supported",
    typicalPermitKinds: ["Registration"],
    applicableFields: ["vin", "make", "model", "color", "licensePlate"],
    icon: "car",
  },
  {
    category: "Snowmobile",
    group: "Powersport",
    structuralType: "Vehicle",
    displayLabel: "Snowmobile",
    defaultUsageTrackingMode: "Both",
    typicallyHasEngine: true,
    vinDecodeSupport: "BestEffort",
    typicalPermitKinds: ["Registration", "TrailPass"],
    applicableFields: ["vin", "make", "model", "color", "trackLengthIn"],
    icon: "snowflake",
  },
  {
    category: "PowerBoat",
    group: "Water",
    structuralType: "Boat",
    displayLabel: "Power Boat",
    defaultUsageTrackingMode: "Both",
    typicallyHasEngine: true,
    vinDecodeSupport: "None",
    typicalPermitKinds: ["Registration"],
    applicableFields: ["hin", "hullMaterial", "hullType", "driveType", "lengthFt", "beamFt", "make", "model", "color"],
    icon: "ship",
  },
  {
    category: "Sailboat",
    group: "Water",
    structuralType: "Boat",
    displayLabel: "Sailboat",
    defaultUsageTrackingMode: "Hours",
    typicallyHasEngine: false,
    vinDecodeSupport: "None",
    typicalPermitKinds: ["Registration"],
    applicableFields: ["hin", "hullMaterial", "hullType", "keelType", "mastHeightFt", "mastCount", "lengthFt", "beamFt", "make", "model", "color"],
    icon: "sailboat",
  },
  {
    category: "Pwc",
    group: "Water",
    structuralType: "Boat",
    displayLabel: "Personal Watercraft",
    defaultUsageTrackingMode: "Hours",
    typicallyHasEngine: true,
    vinDecodeSupport: "None",
    typicalPermitKinds: ["Registration"],
    applicableFields: ["hin", "hullMaterial", "lengthFt", "beamFt", "make", "model", "color"],
    icon: "ship",
  },
  {
    category: "RidingMower",
    group: "Equipment",
    structuralType: "Equipment",
    displayLabel: "Riding Mower",
    defaultUsageTrackingMode: "Hours",
    typicallyHasEngine: true,
    vinDecodeSupport: "None",
    typicalPermitKinds: [],
    applicableFields: ["cuttingWidthIn"],
    icon: "tractor",
  },
  {
    category: "UtilityTrailer",
    group: "Trailer",
    structuralType: "Trailer",
    displayLabel: "Utility Trailer",
    defaultUsageTrackingMode: "None",
    typicallyHasEngine: false,
    vinDecodeSupport: "None",
    typicalPermitKinds: ["Registration"],
    applicableFields: ["ballSizeIn", "maxLoadLbs", "licensePlate"],
    icon: "container",
  },
];
